version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: threatdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - threat-db-data:/var/lib/postgresql/data

volumes:
  threat-db-data:
